[project]
name = "abizza"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "robotframework>=6.1.1",
    "robotframework-browser>=7.0.0",
]
